#ifndef CLOUD_SERVER_LOG_PUBLISHER_THREAD_INCLUDE_H
#define CLOUD_SERVER_LOG_PUBLISHER_THREAD_INCLUDE_H

#include "../../internal/03-thread/02-LogPublisherThread.h"

#endif // CLOUD_SERVER_LOG_PUBLISHER_THREAD_INCLUDE_H
