#ifndef CLOUD_SERVER_LOG_PUBLISHER_THREAD_PUBLIC_H
#define CLOUD_SERVER_LOG_PUBLISHER_THREAD_PUBLIC_H

#include "../01-interface/02-ILogPublisher.h"

#endif // CLOUD_SERVER_LOG_PUBLISHER_THREAD_PUBLIC_H
